---
layout: post
date: 2022-07-18
title: "Introduced 'error' Object"
author: Graur
---

Since 0.25.0 version it is possible to use
[`error`](https://github.com/objectionary/home/blob/master/objects/org/eolang/error.eo)
object just like this:

```
[x] > check
  if. > @
    x.eq 0
    error "Can't divide by zero"
    42.div x
```

Here, the object `error` causes program termination at the first attempt to dataize it.
It encapsulates any other object, which can play the role of an exception that is
floating to the upper level.

<!--more-->

You can also use `try` object that enables catching of `error` objects and extracting exceptions from them.

Visit our [paper](https://arxiv.org/abs/2206.02585) to get more details.
